### PR TITLE
stdblas

### PR DESCRIPTION
**Pull request by rasolca**
Note: links in the slides are broken until this PR is merged.

### CODE REVIEW

**Review by msimberg — COMMENTED** [review]
Looks good to me, thanks @rasolca. Perhaps it's worth adding a word about LAPACK (not being included)?

**Comment by rasolca** [comment]
Thanks. I added an introduction slide in the beginning.

**Comment by rasolca** [comment]
And modified the final slide as well.

**Comment by iomaganaris** [comment]
I skimmed through the slides/code and managed to build it as well. LGTM 👍

**Comment by rasolca** [comment]
Thanks for the reviews!

**Pull request merged**
